import { expect, test } from "@playwright/test";

test("publishes a machine-readable capability report", async ({ page }) => {
  await page.goto("/");
  await expect(page.locator("h1")).toContainText("PS3 homebrew in Safari");
  const report = await page.evaluate(async () => window.__rpcs3Web.runSmokeTest());
  expect(report.schemaVersion).toBe(1);
  expect(report.webAssembly).toBe(true);
  expect(report.worker.worker.state).toBe("passed");
  expect(report.worker.dynamicWasm.state).toBe("passed");
  expect(report.crossOriginIsolated).toBe(true);
  expect(report.sharedArrayBuffer).toBe(true);
  expect(report.coreProbe?.loaded).toBe(true);
  expect(report.coreProbe?.memoryTestMask).toBe(0);
  expect(report.coreProbe?.mappedPages).toBe(5);
  expect(report.coreProbe?.residentPages).toBe(2);
  expect(report.coreProbe?.abiVersion).toBe(7);
  expect(report.coreProbe?.ppuTestMask).toBe(0);
  expect(report.coreProbe?.ppuInstructions).toBe(46);
  expect(report.coreProbe?.ppuResult).toBe(70);
  expect(report.coreProbe?.ppuLoadedResult).toBe(70);
  expect(report.coreProbe?.ppuSupportedOpcodes).toBe(92);
  expect(["passed", "unsupported"]).toContain(report.worker.guestHomebrew.state);
  expect(report.worker.guestFrame?.fixture).toBe("gs_gcm_basic_triangle.elf");
  expect(report.worker.guestFrame?.flips).toBe(1);
  expect(report.worker.guestFrame?.commandWords).toBe(140);
  expect(report.worker.guestFrame?.vertices).toBe(3);
  expect(report.coreProbe?.elfProbe?.loaded).toBe(true);
  expect(report.coreProbe?.elfProbe?.testMask).toBe(0);
  expect(report.coreProbe?.elfProbe?.segments).toBe(2);
  expect(report.coreProbe?.elfProbe?.entry).toBe(0x1022c);
  expect(report.coreProbe?.elfProbe?.instructions).toBe(3291);
  expect(report.coreProbe?.elfProbe?.stopReason).toBe(5);
  expect(report.coreProbe?.elfProbe?.pc).toBe(0x25bbc);
  expect(report.coreProbe?.elfProbe?.hleCalls).toBe(30);
  expect(report.coreProbe?.elfProbe?.hleNid).toBe(0x24a1ea07);
  expect(report.coreProbe?.elfProbe?.syscalls).toBe(1);
  expect(report.coreProbe?.elfProbe?.lastSyscall).toBe(352);

  const repeated = await page.evaluate(async () => window.__rpcs3Web.runSmokeTest());
  expect(repeated.coreProbe?.memoryTestMask).toBe(0);
  expect(repeated.coreProbe?.ppuTestMask).toBe(0);
  expect(repeated.coreProbe?.elfProbe?.testMask).toBe(0);
  await expect(page.locator("#evidence")).toContainText('"schemaVersion": 1');
});
